name: test
on: push
jobs:
  test:
    runs-on: ubuntu-22.04
    container: ryuichiueda/ubuntu22.04-ros2:latest
    steps:
      - uses: actions/checkout@v2
      - name: build and test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          rsync -av ./ /root/ros2_ws/src/mypkg/
          set +xv
          cd /root/ros2_ws/src
          git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}git@github.com:fukuda602/person_msgs.git
          #rosdep update
          #rosdep install -i --from-path src --rosdistro humble -y
          bash -xv ./mypkg/test/test.bash /root
